-- MySQL Script generated by MySQL Workbench
-- 2018年12月24日 星期一 16时36分03秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema china_used_car_estimate
--
-- 中国二手车估值系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car` DEFAULT CHARACTER SET utf8 ;
USE `car` ;


CREATE TABLE IF NOT EXISTS `car`.`crawler_guazi_car_source` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` varchar(200) DEFAULT NULL COMMENT '来源网址',
  `detail_name` varchar(64) DEFAULT NULL COMMENT '款型描述',
  `year` varchar(16) DEFAULT NULL COMMENT '上牌年',
  `mile` varchar(32) DEFAULT NULL COMMENT '公里数(万)',
  `city` varchar(32) DEFAULT NULL COMMENT '上牌地',
  `color` varchar(16) DEFAULT NULL COMMENT '颜色',
  `price` decimal(7,2) DEFAULT NULL COMMENT '价格(万元)',
  `transfer_owner` varchar(12) DEFAULT NULL COMMENT '过户次数',
  `annual_insurance` varchar(32) DEFAULT NULL COMMENT '年检到期时间',
  `compulsory_insurance` varchar(32) DEFAULT NULL COMMENT '交强险到期时间',
  `business_insurance` varchar(32) DEFAULT NULL COMMENT '商业险到期时间',
  `description` text DEFAULT NULL COMMENT '车况描述',
  `description_time` varchar(32) DEFAULT NULL COMMENT '车况采集时间',
  `region` varchar(32) DEFAULT NULL COMMENT '地区或看车地点',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '抓取时间',
  PRIMARY KEY (`id`),
  KEY i_create_time(create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='抓取瓜子二手车平台车源';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
